### ISSUE TITLE
After Re-Opening Unity, SkAdNetworkIds are Null/Empty for iOS

### ISSUE THREAD

**Issue by clehnert** [appodeal/appodeal-unity-demo#13]
In the latest Appodeal Unity SDK (2.14.2), an Appodeal menu item is created. This gives access to the Appodeal Settings menu. This menu contains an iOS option "Add SkAdNetworkIds". When clicking this item, it appears (digging into the C# code - private static IEnumerator GetSkaNetworkIds()) that the Network Ids are downloaded from https://mw-backend.appodeal.com/v1/skadnetwork/. If you build your project, these items are added to the XCode Info.plist. If you close and re-open Unity, re-build, and replace the XCode project, these Network Ids are not added because they were never downloaded during the current Unity session. The Appodeal Settings menu needs to be re-opened,  "Add SkAdNetworkIds" needs to be unchecked, and then re-checked for the download to occur and the Info.plist to be properly updated.

Expected Behavior: During the build process (public static void updateInfoPlist(BuildTarget buildTarget, string buildPath)???), the SkAdNetworkIds should be downloaded if AppodealSettings.Instance.IOSSkAdNetworkItems == true && (AppodealInternalSettings.SKAdNetworkIdentifiers == null || AppodealInternalSettings.SKAdNetworkIdentifiers.Count <= 0)

Thanks

**Comment by KulArtsiom** [comment]
@clehnert Will be fixed in the 2.14.3 version. Thank you.
