### ISSUE TITLE
Unable to add package 3.1.3

### ISSUE THREAD

**Issue by walektine** [appodeal/appodeal-unity-demo#23]
Unity 2021.3.24, Mac OS 13.6.1 (Intel)

Trying to add Package via Package Manager, all previous steps are done

There is issue
<img width="1487" alt="Screenshot 2023-11-09 at 14 27 50" src="https://github.com/appodeal/appodeal-unity-demo/assets/127826967/696b2b11-e533-4b52-ac8f-9fdd398eb28c">

**Comment by DmitriiFeshchenko** [comment]
Hi, @walektine!

As I can see from the screenshot you provided, the EDM plugin is installed manually. Could you please remove it and install the UPM version of this plugin as stated in the [documentation](https://docs.appodeal.com/unity/get-started?distribution=upm#step-1-import-sdk)?

<img width="873" alt="image" src="https://github.com/appodeal/appodeal-unity-demo/assets/43773640/3fc03ecd-fbbb-452f-8afc-e2a8036a11b4">

If you have any further questions, I recommend you to [contact our support team](https://faq.appodeal.com/en/articles/96628-technical-support) as they will respond much faster.

Best Regards,
