### ISSUE TITLE
'myappname.app/Frameworks/OMSDK_Appodeal.framework/OMSDK_Appodeal' contains bitcode in XCode 16.0

### ISSUE THREAD

**Issue by MaxKillMax** [appodeal/appodeal-unity-demo#39]
Unity 2022.3.37f1
MacOS Sequoia 15.0.1 (apple silicon)
XCode 16.0

After the new versions of mac and xcode, the archive is distributed with an error as in the header. I can't roll back to the previous version of XCode without rolling back macOS and losing all data. Tried manually disabling bitcode from you, and various other methods, but it didn't work

Looked up solutions to similar headings:
1. https://stackoverflow.com/questions/78993520/invalid-executable-the-executable-appname-app-frameworks-hermes-framework-herm

2. https://medium.com/@abdulahad2024/fixing-bitcode-issues-in-xcode-16-how-to-resolve-invalid-executable-errors-when-uploading-ios-da07a5a39c7c

3. https://forums.developer.apple.com/forums/thread/763562

Image of exception:
![image](https://github.com/user-attachments/assets/8bf9b5ea-bf9d-4f41-87a3-1c128dbe0f97)

**Comment by Khrolovich** [comment]
Hi @MaxKillMax!

For Appodeal SDK v3.3.3, try to add these lines in the Podfile and reinstall pods:

```
post_install do |installer|
  xcframework_path = "#{installer.sandbox.root}/OMSDK_Appodeal"

  Dir.glob("#{xcframework_path}/**/*.framework/OMSDK_Appodeal").each do |binary|
    if File.exist?(binary)
      puts "Stripping bitcode from: #{binary}"
      system("xcrun bitcode_strip #{binary} -r -o #{binary}")
    end
  end
end
```

For Appodeal SDK v3.4.0-beta.1, disable bitcode for SmaatoSDK: 
```
post_install do |installer|
  xcframework_path = "#{installer.sandbox.root}/smaato-ios-sdk/vendor"

  Dir.glob("#{xcframework_path}/**/*.framework/OMSDK_Smaato").each do |binary|
    if File.exist?(binary)
      puts "Stripping bitcode from: #{binary}"
      system("xcrun bitcode_strip #{binary} -r -o #{binary}")
    end
  end
end
```
Another option is to delete Smaato Adapter in the [Dependency Manager](https://docs.appodeal.com/unity/next/advanced/appodeal-plugin-manager).

**Comment by MaxKillMax** [comment]
Hi.
I forgot to specify that I am using version 3.3.3 of Appeal

I tried putting the code for 3.3.3 in 3 different places (because I didn't know exactly how order affects final result), but none of them helped and error is exactly same

I added these lines to the podfile and then did `pod install` afterwards.

![telegram-cloud-photo-size-2-5199769446611281138-y](https://github.com/user-attachments/assets/c9b736d7-1625-4162-b367-db773c526077)
-----
-----
![telegram-cloud-photo-size-2-5199769446611281157-y](https://github.com/user-attachments/assets/e775e15f-a9c3-43be-a673-12ee1d135cc1)
-----
-----
![telegram-cloud-photo-size-2-5199769446611281158-y](https://github.com/user-attachments/assets/78391cad-bbed-4ca4-a9bd-a0aecca54ab3)
-----
-----
<img width="645" alt="image" src="https://github.com/user-attachments/assets/cf3144ca-0143-4c51-a8ab-654e103cbaab">


> Hi @MaxKillMax!
> 
> For Appodeal SDK v3.3.3, try to add these lines in the Podfile and reinstall pods:
> 
> ```
> post_install do |installer|
>   xcframework_path = "#{installer.sandbox.root}/OMSDK_Appodeal"
> 
>   Dir.glob("#{xcframework_path}/**/*.framework/OMSDK_Appodeal").each do |binary|
>     if File.exist?(binary)
>       puts "Stripping bitcode from: #{binary}"
>       system("xcrun bitcode_strip #{binary} -r -o #{binary}")
>     end
>   end
> end
> ```

**Comment by Khrolovich** [comment]
It should work if you see logs of bitcode disabling during pods installation:

<img width="743" alt="Screenshot 2024-10-08 at 13 14 05" src="https://github.com/user-attachments/assets/3a73ca4a-dfce-442e-8a4b-e3ac6019c1da">

If you see the logs and the issue is reproducing, most likely you need to clean build folder. 

Try this way: close Xcode -> "pod deintegrate" -> "pod install" -> check that you see logs of bitcode disabling (like on the screenshot above) -> open XCode -> Clean Build Folder (Product -> Clean Build Folder) -> Archive.

**Comment by MaxKillMax** [comment]
There are messages in the console
![telegram-cloud-photo-size-2-5199769446611281446-y](https://github.com/user-attachments/assets/d15e6840-f3b2-45c3-b14d-0cf81cdc910d)

I did everything in the same order, the error is still there

Just in case, I'll describe the order:
Made a build in Unity -> Added lines to Podfile -> Made pod deintegrate -> Made pod install -> Opened xcworkspace -> Cleared Build Folder -> Started making Archive -> Started making Distribute App to App Store Connect

It might also matter that I commented out some of the Appodeal Dependencies.xml because they give an error at the `pod install` too in new Xcode 16 (except for firebase, which is duplicated with the firebase plugin itself):
<img width="1244" alt="image" src="https://github.com/user-attachments/assets/dd2b254b-d7f6-4f15-bec6-90b644f5631b">

**Comment by MaxKillMax** [comment]
Thank you! Removing of empty space in folder name fixed error
Remains this warnings. Is it OK?

<img width="665" alt="image" src="https://github.com/user-attachments/assets/b6758162-1c65-4ed1-b510-b0f1d3a09e9e">
------
![Uploading image.png…]()

**Comment by Khrolovich** [comment]
Yes, you can ignore these warnings. The dSYM files are needed for symbolizing crash reports, and their absence does not affect the app’s performance.
