### ISSUE TITLE
Missing AppodealController

### ISSUE THREAD

**Issue by TonGarcia** [appodeal/appodeal-unity-demo#40]
I cloned this demo Repository, but it is missing the AppodealController (I am running v3.3.3 on MacOS Silicon, but it is not about the MacOS it is just about missing Script):

<img width="1438" alt="Screenshot 2024-10-08 at 21 51 13" src="https://github.com/user-attachments/assets/2b02954f-adaf-4dd9-a830-a95790d43ac0">

**Comment by Khrolovich** [comment]
Hi @TonGarcia ,

Try to reimport the usage sample in Package Manager.

<img width="827" alt="Screenshot 2024-10-09 at 10 25 53" src="https://github.com/user-attachments/assets/0eca1e6a-3ffb-424a-9b26-e5a986d926e9">

**Comment by TonGarcia** [comment]
@Khrolovich thank you so much, vova, it did the trick!

**Comment by TonGarcia** [comment]
@Khrolovich thank you so much, vova, it did the trick!
